version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current-stretch-browsers-legacy
    working_directory: ~/cncf
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci && rm -r node_modules && npx npm-force-resolutions && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run tests
          command: npm test
      - store_artifacts:
          path: ~/cncf/coverage
